TG-49-50: Shared Inputs
BaSP-m2022/samuel-trackgenix-app pull request #13
Opened 2022-06-06 18:19 UTC by pcorreadev

2022-06-06 18:49 UTC, samueltrilloRR requested changes

2022-06-06 18:49 UTC, samueltrilloRR commented on src/Components/Shared/Input/InputSelect/Index.js
> +            {`${item.params}`}
Should return the "label" value

2022-06-06 18:49 UTC, samueltrilloRR commented on src/Components/Shared/Input/InputSelect/Index.js
> +          <option selected={Boolean(item._id === itemValue)} key={item._id} value={item._id}>
"_id" prop does not exist in the objects that are defined inside "arrayToMap" array

2022-06-06 18:49 UTC, samueltrilloRR commented on src/Components/Shared/Input/InputSelect/select.module.css
> +select {
Replace this "styled tag" with a class

2022-06-06 18:49 UTC, samueltrilloRR commented on src/Components/Shared/Input/Input.module.css
> +input {
Replace this "styled tag" with a class. Also, this stylesheet should be rename to "inputText.module.css" to change the initial letter (should no start with capital letter) and the file should be placed inside new folder called InputText

2022-06-06 18:49 UTC, samueltrilloRR commented on src/Components/Shared/Input/index.js
> +import styles from './Input.module.css';
Should be placed inside new folder called "InputText" to keep the consistency

2022-06-06 18:49 UTC, samueltrilloRR commented on src/Components/Shared/Input/index.js
> +const Input = (name, type, placeholder, value, onChange, required, className = styles) => {
It should receive a "label" prop to show it and link it with the created input

2022-06-06 18:49 UTC, samueltrilloRR commented on src/Components/Shared/Input/index.js
> +    <input
Should be an "label" tag linked with the "input" tag

2022-06-06 18:54 UTC, samueltrilloRR requested changes

2022-06-07 12:49 UTC, samueltrilloRR requested changes

2022-06-07 12:49 UTC, samueltrilloRR commented on src/Components/Shared/Input/InputSelect/Index.js
> +              {`${item.params}`}
Params should be renamed into "label"

2022-06-07 12:49 UTC, samueltrilloRR commented on src/Components/TimeSheets/Form/index.js
> +      params: `${item.name}`
"params" should be rename to a properly name property as "label"

2022-06-07 16:34 UTC, OctavioRodriguezPaseyro commented on src/Components/Shared/Input/InputText/inputText.module.css
>  }
no newline at end of inputText.module.css

2022-06-07 16:34 UTC, OctavioRodriguezPaseyro commented on src/Components/Shared/Input/InputSelect/inputSelect.module.css
>    }
no newline at end of inputSelect.module.css

2022-06-07 18:05 UTC, OctavioRodriguezPaseyro approved these changes

2022-06-07 18:43 UTC, samueltrilloRR approved these changes

2022-06-07 18:43 UTC, merged