TG 60: Admins
BaSP-m2022/samuel-trackgenix-app pull request #15
Opened 2022-06-06 19:22 UTC by OctavioRodriguezPaseyro

This pull request will be merged when all the shared components are correctly added to it.

2022-06-07 03:15 UTC, gavafue commented on src/Components/Admins/Form/form.module.css
> +
Remember keep the consistance of the CSS, .container should to be before to .adminForm

2022-06-07 03:16 UTC, gavafue commented on src/Components/Admins/Form/index.js
> +        alert(data.message);
What is the function of this alerts?

2022-06-07 03:21 UTC, gavafue commented on src/Components/Projects/Table/index.js
> +                <td>{project.members.name}</td>
Thank you for solve the projects' entity problem

2022-06-07 03:21 UTC, gavafue reviewed
Check it that you have some comments ando conflicts on your PR

2022-06-08 02:54 UTC, gavafue approved these changes

2022-06-08 04:33 UTC, paurinaldi commented
I see that Gabi already approved but there are two things I noticed: Your form is a row, it should be a column, as the ones on figma we said we were going to base our styling on. Also, the add button is in a totally different color and format as all the others, we agreed add and submit would use the Button's scondary style.

2022-06-09 16:36 UTC, samueltrilloRR requested changes

2022-06-09 16:36 UTC, samueltrilloRR commented on src/Components/Admins/Form/form.module.css
> +	box-shadow:0 0 10px #999;
Bad indentation

2022-06-09 16:36 UTC, samueltrilloRR commented on src/Components/Admins/Form/index.js
>  function Form() {
Transform function into arrow function (EM6)

2022-06-09 19:24 UTC, samueltrilloRR requested changes

2022-06-09 19:24 UTC, samueltrilloRR commented on src/Components/Admins/index.js
> +      <Button label="Add new admin +" onClick={() => (window.location = `/admins/form/`)} />
window.location should be replaced with React router hook

2022-06-09 23:02 UTC, OctavioRodriguezPaseyro commented on src/Components/Admins/index.js
> +      <Button label="Add new admin +" onClick={() => (window.location = `/admins/form/`)} />
line 26 was changed on last commit "TG-60: correction"

<Button label="Add new admin +" onClick={() => history.push(`/admins/form/`)} />

2022-06-10 02:27 UTC, samueltrilloRR approved these changes

2022-06-10 13:24 UTC, merged