TG-63: Include shared components into projects
BaSP-m2022/samuel-trackgenix-app pull request #22
Opened 2022-06-07 22:27 UTC by gavafue

2022-06-08 04:43 UTC, paurinaldi commented on src/Components/Projects/index.js
> -//import styles from './projects.module.css';
Gabi, maybe you could've added a stylesheet for Project's index, so you could format the contents a little more like figma's references. Also, today we agreed we would use the secondary style on Button component for submit and add.

2022-06-08 15:13 UTC, paurinaldi approved these changes

2022-06-09 18:22 UTC, samueltrilloRR requested changes

2022-06-09 18:22 UTC, samueltrilloRR commented on src/Components/Projects/Form/form.module.css
> +}
Tags don't work properly with css modules. Please, replace them with classes

2022-06-09 18:22 UTC, samueltrilloRR commented on src/Components/Projects/Form/index.js
> +    return { id: employee._id, optionContent: employee.firstName + employee.lastName };
Replace oprionContent concat using ES6

2022-06-09 18:22 UTC, samueltrilloRR commented on src/Components/Projects/Form/index.js
> +        <InputText
InputText and InputSelect components already have label tag, so label tags on this component should be deleted, and pass the label to the InputText and InputSelect components

2022-06-09 18:22 UTC, samueltrilloRR commented on src/Components/Projects/index.js
> +  window.location = `/projects/form/${id}`;
Should use React Router's hook to handle redirection

2022-06-09 18:22 UTC, samueltrilloRR commented on src/Components/Projects/index.js
> +  const URL = `${process.env.REACT_APP_API_URL}`;
On this case, is not necessary a concatenation

2022-06-09 18:22 UTC, samueltrilloRR commented on src/Components/Projects/index.js
> +            onClick={() => (window.location = '/projects/form')}
Use React Router's hooks to handle this

2022-06-09 23:13 UTC, OctavioRodriguezPaseyro approved these changes

2022-06-10 02:28 UTC, samueltrilloRR approved these changes

2022-06-10 13:24 UTC, merged