BaSP-TG-61-superAdmins
BaSP-m2022/samuel-trackgenix-app pull request #24
Opened 2022-06-08 02:17 UTC by paurinaldi

2022-06-08 13:46 UTC, OctavioRodriguezPaseyro requested changes

2022-06-08 17:16 UTC, OctavioRodriguezPaseyro approved these changes

2022-06-09 18:29 UTC, samueltrilloRR commented on src/Components/SuperAdmins/index.js
> +  const deleteSuperAdmin = (string) => {
Change "string" parameter name to "superAdminId" for consistency

2022-06-09 19:26 UTC, samueltrilloRR approved these changes

2022-06-10 13:24 UTC, merged