TG 71: employees redux
BaSP-m2022/samuel-trackgenix-app pull request #31
Opened 2022-06-12 18:05 UTC by OctavioRodriguezPaseyro

This PR updates previous week's work by implementing Redux to the employees screen.

2022-06-16 02:13 UTC, MarciaBeron commented
I think that for the constants and reducers for the table, we should use the plural form of "employee" since we are getting all of them.

2022-06-16 13:01 UTC, samueltrilloRR requested changes

2022-06-16 13:03 UTC, samueltrilloRR commented on src/Components/Employees/Form/index.js
> +    dispatch(addOrEditEmployee(options));
It's necessary because you can be more consistent with the usage of Redux, splitting the different actions to be more clear about what are you doing in each time.

2022-06-16 16:35 UTC, gavafue commented on src/redux/employees/actions.js
> +
On the list you're not adding the new employee

2022-06-17 19:52 UTC, samueltrilloRR submitted a review, later dismissed

2022-06-17 19:56 UTC, samueltrilloRR requested changes

2022-06-17 19:56 UTC, samueltrilloRR commented on src/redux/employees/thunks.js
> +        dispatch(getEmployeeSuccess(response.data));
You are not handling error case un the get, post and put methods

2022-06-17 21:54 UTC, samueltrilloRR approved these changes

2022-06-18 15:39 UTC, merged