TG-72: Timesheets entity
BaSP-m2022/samuel-trackgenix-app pull request #32
Opened 2022-06-14 15:20 UTC by gavafue

2022-06-16 02:22 UTC, MarciaBeron commented
When editing or deleting, if we go back it keeps the last timesheet info, we should have an action to clean Redux in order to avoid such problem.

2022-06-16 23:18 UTC, samueltrilloRR commented on src/redux/timesheet/thunks.js
> +        if (isValid) {
isValid is not necessary because you can check the "error" prop that comes within the response's object. Also this check should be placed inside the second then() method, after the json() method is resolved

2022-06-16 23:18 UTC, samueltrilloRR commented on src/redux/timesheet/reducer.js
> +  pending: false,
isPending is more appropriate name than only pending

2022-06-17 19:53 UTC, samueltrilloRR requested changes

2022-06-17 19:53 UTC, samueltrilloRR commented on src/redux/timesheet/thunks.js
> +        console.log(error);
Delete console log

2022-06-18 12:38 UTC, samueltrilloRR approved these changes

2022-06-18 16:46 UTC, LastStance21 approved these changes
**Tested succesfully, and passed all the tests**

2022-06-19 14:56 UTC, merged