Feature/TG-70-Projects
BaSP-m2022/samuel-trackgenix-app pull request #33
Opened 2022-06-14 16:01 UTC by paurinaldi

2022-06-16 01:33 UTC, MarciaBeron commented
There seems to be a problem with the select input for members, when editing a project it doesn't bring any members.

2022-06-16 16:38 UTC, gavafue commented on src/Components/Projects/index.js
> +    dispatch(cleanSelectedProject());
You could do this dispatch into the UseEffect of the line 34, just above the GetProjects

2022-06-16 16:40 UTC, gavafue reviewed
I think all is ok

2022-06-16 22:07 UTC, samueltrilloRR requested changes

2022-06-16 22:07 UTC, samueltrilloRR commented on src/redux/projects/thunks.js
> +        return response.json();
isValid is not necessary because you can check the "error" prop that comes within the response's object. Also this check should be placed inside the second then() method, after the json() method is resolved

2022-06-16 22:07 UTC, samueltrilloRR commented on src/redux/projects/reducer.js
> +  pending: false,
isPending is more appropriate name than only pending

2022-06-16 22:07 UTC, samueltrilloRR commented on src/Components/Projects/index.js
> +          setShowModal={(boolean) => dispatch(showDeleteMessage(boolean))}
boolean parameter name should be replaced with other, since boolean is a type of data

2022-06-17 16:00 UTC, samueltrilloRR approved these changes

2022-06-18 15:52 UTC, merged