BaSP-TG-73: Tasks completed
BaSP-m2022/samuel-trackgenix-app pull request #34
Opened 2022-06-14 21:14 UTC by MarciaBeron

2022-06-16 17:23 UTC, gavafue reviewed
I think all is ok

2022-06-16 17:23 UTC, gavafue approved these changes

2022-06-16 22:20 UTC, samueltrilloRR requested changes

2022-06-16 22:20 UTC, samueltrilloRR commented on src/redux/tasks/thunks.js
> +        if (isValid) {
isValid is not necessary because you can check the "error" prop that comes within the response's object. Also this check should be placed inside the second then() method, after the json() method is resolved

2022-06-17 19:26 UTC, OctavioRodriguezPaseyro approved these changes

2022-06-17 20:35 UTC, OctavioRodriguezPaseyro commented on src/redux/tasks/thunks.js
> +      .catch((error) => {
catch should be used for unexpected errors
should use an if else like in delete to handle the expected errors

2022-06-18 16:02 UTC, paurinaldi approved these changes

2022-06-18 16:35 UTC, samueltrilloRR approved these changes

2022-06-18 17:13 UTC, merged