BaSP-TG-75: Applied redux to SuperAdmin
BaSP-m2022/samuel-trackgenix-app pull request #35
Opened 2022-06-14 23:33 UTC by MarciaBeron

2022-06-15 15:47 UTC, paurinaldi commented on src/redux/superadmin/thunks.js
> +          console.log('log de if', response);
delete this and 'log de else' console.log

2022-06-16 22:30 UTC, samueltrilloRR requested changes

2022-06-16 22:30 UTC, samueltrilloRR commented on src/redux/superadmin/thunks.js
> +        if (isValid) {
isValid is not necessary because you can check the "error" prop that comes within the response's object. Also this check should be placed inside the second then() method, after the json() method is resolved

2022-06-16 22:30 UTC, samueltrilloRR commented on src/redux/superadmin/reducers.js
> +        })
Is missing "pending" state change.

2022-06-16 22:30 UTC, samueltrilloRR commented on src/Components/SuperAdmins/index.js
> +        setShowModal={(boolean) => dispatch(showDeleteMessage(boolean))}
boolean parameter name should be replaced with other, since boolean is a type of data

2022-06-17 19:23 UTC, OctavioRodriguezPaseyro commented on src/redux/superadmin/reducers.js
> +  pending: false,
could be isPending for consistency

2022-06-17 21:02 UTC, pcorreadev commented
Modal displaying this message when editing and submiting an invalid email
"Cannot read properties of undefined (reading '_id')"

2022-06-19 13:45 UTC, samueltrilloRR approved these changes

2022-06-19 18:13 UTC, merged