BaSP-TG-74: Admins
BaSP-m2022/samuel-trackgenix-app pull request #36
Opened 2022-06-15 01:57 UTC by pcorreadev

2022-06-15 14:59 UTC, paurinaldi reviewed
Apart from what you said on the meet about the gender value, the form is also not bringing back the date value when you edit. Maybe you should change the date input format in order for it to work correctly. Another thing I noticed on the deployment is that when for some reason you get a feedback message saying there was an error when trying to submit, once you close it it redirects you to the table, when I think the idea would be to close and be able to amend the error, not to exit the form.

2022-06-16 17:40 UTC, gavafue reviewed
I did some comments, check it

2022-06-16 23:03 UTC, samueltrilloRR requested changes

2022-06-16 23:03 UTC, samueltrilloRR commented on src/redux/admins/reducer.js
> +  pending: false,
isPending is more appropriate name than only pending

2022-06-16 23:03 UTC, samueltrilloRR commented on src/Components/Admins/Table/index.js
> +          setShowModal={(boolean) => dispatch(showDeleteMessage(boolean))}
boolean parameter name should be replaced with other, since boolean is a type of data

2022-06-16 23:03 UTC, samueltrilloRR commented on src/Components/Admins/Table/index.js
> +        setShowModal={(boolean) => dispatch(showDeleteMessage(boolean))}
boolean parameter name should be replaced with other, since boolean is a type of data

2022-06-17 19:31 UTC, OctavioRodriguezPaseyro commented on src/Components/Admins/Form/index.js
> +  const title = isAdminSelected ? `Editing ${nameValue} admin information.` : 'Add an Admin';
change nameValue to adminSelected.name so that it won't change as the users are editing the form.

2022-06-18 12:42 UTC, samueltrilloRR approved these changes

2022-06-19 00:47 UTC, merged