TG-82: setup week 14
BaSP-m2022/samuel-trackgenix-app pull request #38
Opened 2022-06-17 17:53 UTC by OctavioRodriguezPaseyro

Installed the following libraries:
· React hook form + resolvers
· Joi

2022-06-17 18:58 UTC, gavafue approved these changes

2022-06-18 12:50 UTC, samueltrilloRR requested changes

2022-06-18 12:50 UTC, samueltrilloRR commented on jsconfig.json
> +}
Is misssing the property "include: ["src"]"

2022-06-18 15:33 UTC, samueltrilloRR approved these changes

2022-06-18 15:33 UTC, merged