TG-100: Navbar modifications
BaSP-m2022/samuel-trackgenix-app pull request #49
Opened 2022-06-21 20:15 UTC by paurinaldi

Developed logic so that Navbar shows different list items at employee's views, also added photo and name of our provisory "logged" employee, and default photo for the rest of the routes. Still working on setting the role for employee's routes. 

employee's routes are:
/employee/home
/employee/profile
/employee/projects
/employee/timesheet

2022-06-23 17:51 UTC, OctavioRodriguezPaseyro commented on src/Components/Shared/Navbar/navbar.module.css
> +
please remove this empty line

2022-06-24 13:38 UTC, samueltrilloRR requested changes

2022-06-24 13:38 UTC, samueltrilloRR commented on src/Components/Shared/Navbar/index.js
> +    employeeLogged.firstName && employeeLogged.lastName != undefined
I think this could be replaced with 
``(employeeLogged.firstName && employeeLogged.lastName)
? `${employeeLogged.firstName} ${employeeLogged.lastName}`
      : '' ``

2022-06-24 13:38 UTC, samueltrilloRR commented on src/Components/Shared/Navbar/index.js
> +            {navBarItems != employeeNavbar ? (
You can use "location.includes('/employee/')" instead comparing two arrays

2022-06-25 15:33 UTC, samueltrilloRR approved these changes

2022-06-25 15:33 UTC, merged