TG-53: Shared modal
BaSP-m2022/samuel-trackgenix-app pull request #8
Opened 2022-06-04 17:59 UTC by OctavioRodriguezPaseyro

WIP: Admins implementation

2022-06-05 17:41 UTC, paurinaldi requested changes
I deleted the previous comment since Samuel made clear that the modal should be empty an receive children, which will be the DeleteMessage, or ConfirmMessage components we are developing.

2022-06-05 19:33 UTC, samueltrilloRR requested changes
Needs to be modified.
-Must receive a children
-Must have only a cross to close the modal

2022-06-05 20:03 UTC, samueltrilloRR requested changes

2022-06-05 20:03 UTC, samueltrilloRR commented on src/Components/Shared/Modal/modal.module.css
> +}
Does not exist an hr tag into modal, so please, delete this (friendly reminder: try to avoid using hr)

2022-06-05 20:03 UTC, samueltrilloRR commented on src/Components/Shared/Modal/modal.module.css
> +
Delete blank space please

2022-06-06 19:00 UTC, samueltrilloRR commented on src/Components/Admins/Table/index.js
> +  const [isAdding, setIsAdding] = useState(false);
If you are deleting, should be renamed to "isDeleting"

2022-06-06 19:01 UTC, samueltrilloRR commented on src/Components/Admins/Table/index.js
> +        <p>Hellooooooooooooooooooooooo</p>
Could you change this with other word?

2022-06-06 19:08 UTC, samueltrilloRR approved these changes

2022-06-06 19:14 UTC, merged